ALTER TABLE INVENTORY ADD Discount FLOAT;

UPDATE INVENTORY SET Discount = 0 WHERE Model = "LXI";
UPDATE INVENTORY SET Discount = 0.1 WHERE Model = "LXI";
UPDATE INVENTORY SET DISCOUNT = 0.12 WHERE MODEL != "VXI" AND MODEL !="LXI";

SELECT CarName FROM INVENTORY WHERE Fueltype = 'Petrol' AND Price = (SELECT MAX(Price) FROM INVENTORY WHERE Fueltype = 'Petrol');

SELECT AVG(Discount), SUM(Discount) FROM INVENTORY WHERE CarName = "Baleno";

SELECT COUNT(CarId) FROM INVENTORY WHERE DISCOUNT = 0;